### ISSUE TITLE
Import_ANDS fails on ArgumentException

### ISSUE THREAD

**Issue by siwei0607** [rd-switchboard/Inference#6]
ubuntu@graphdb:~/RD-Switchboard/Inference/Compiled-26-Nov$ java -jar import_ands-1.4.0.jar 
Neo4J: neo4j-aggregator
XML: xml/
java.lang.IllegalArgumentException: Unable to load file:/home/ubuntu/RD-Switchboard/Inference/Compiled-26-Nov/neo4j-aggregator/conf/neo4j.properties
    at org.neo4j.graphdb.factory.GraphDatabaseBuilder.loadPropertiesFromURL(GraphDatabaseBuilder.java:164)
    at org.neo4j.graphdb.factory.GraphDatabaseBuilder.loadPropertiesFromFile(GraphDatabaseBuilder.java:136)
    at org.rdswitchboard.libraries.neo4j.Neo4jUtils.getGraphDb(Neo4jUtils.java:45)
    at org.rdswitchboard.libraries.neo4j.Neo4jDatabase.<init>(Neo4jDatabase.java:58)
    at org.rdswitchbrowser.importers.rifcs.neo4j.App.processFiles(App.java:145)
    at org.rdswitchbrowser.importers.rifcs.neo4j.App.main(App.java:60)
Caused by: java.io.FileNotFoundException: /home/ubuntu/RD-Switchboard/Inference/Compiled-26-Nov/neo4j-aggregator/conf/neo4j.properties (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at java.io.FileInputStream.<init>(FileInputStream.java:101)
    at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
    at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
    at java.net.URL.openStream(URL.java:1041)
    at org.neo4j.graphdb.factory.GraphDatabaseBuilder.loadPropertiesFromURL(GraphDatabaseBuilder.java:157)
    ... 5 more

**Comment by wizman777** [comment]
Hi  siwei0607 

To use the program, please provide instance of Neo4j database and add path to it into properties/import_ands.properties file. The default properties file expect the Neo4j instance to be located in neo4j-aggregator folder located in the program folder. You can download working neo4j instance from: https://github.com/rd-switchboard/Neo4j-Browser/tree/master/distribution

I will add more human friendly error message to the program,

**Comment by wizman777** [comment]
Hi  siwei0607

Please also take a look to the program usage instructions: https://github.com/rd-switchboard/Inference/tree/master/Importers/ANDS/import_ands
